platform :ios, '10.0'
use_frameworks!

target 'Web3Swift_Example' do
  pod 'Web3Swift.io', :path => '../'
  pod 'SwiftLint', '~> 0.27'
end

target 'Web3Swift_Tests' do
  pod 'Web3Swift.io', :path => '../'
  pod 'SwiftLint', '~> 0.27'
  pod 'Quick', '~> 1.2'
  pod 'Nimble', '~> 7.0'
end
